spring.application.name=SS-College

spring.datasource.url=jdbc:postgresql://REAL_HOST:5432/REAL_DATABASE_NAME
spring.datasource.username=REAL_USERNAME
spring.datasource.password=REAL_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
