spring.application.name=SS-College

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-abcd.render.com:5432/sscollege
spring.datasource.username=muthu
spring.datasource.password=12345

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
