spring.application.name=SS-College
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ss_college;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=kumar
spring.datasource.password=123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update